[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Control"

[general]
import = ["~/.config/alacritty/themes/alabaster_dark.toml"]
live_config_reload = true

[env]
TERM = "alacritty"

[font]
size = 12.0

## [font.normal]
## family = "SF Pro Display"
## style = "Medium"

[keyboard]
